version: "3.8"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_URL=postgresql://user:password@postgres:5432/taskdb
      - MONGO_URI=mongodb://mongo:27017/taskdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEBHOOK_URL=https://webhook.site/123fd346-60dd-4393-8ea4-0b559a358458
    depends_on:
      - postgres
      - mongo
      - redis
    volumes:
      - .:/app
    command: npm run dev

  postgres:
    image: postgres:15
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    volumes:
      - mongo_data:/data/db
  
  worker:
    build: .
    container_name: worker_app
    depends_on:
      - redis
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    command: node src/queue/workers/reminder.worker.js
    volumes:
    - .:/app

  completion_worker:
    build: .
    container_name: completion_worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: node src/queue/workers/completion.worker.js
    volumes:
    - .:/app

  redis:
    image: redis:7
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  mongo_data:
  redis_data: